version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: internapp
    container_name: internapp
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/app
    environment:
      - NODE_ENV=development
      - PORT=8080
    networks:
      - app-network
    command: bash -c "npm install && npm start"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:  